var JSONallOutput200 = {
    "file": {
        "bits_per_sample": 8,
        "file_access_date": "2018-03-03T22:50:00+00:00",
        "file_modify_date": "2018-03-03T17:55:00+00:00",
        "file_name": "test.JPG",
        "file_size": "155 kB",
        "file_type": "JPEG",
        "image_height": 480,
        "image_size": "640x480",
        "image_width": 640,
        "mime_type": "image/jpeg",
        "user_comment": null
    },
    "camera": {
        "compression": "JPEG (old-style)",
        "date_time_original": "2008-10-22T16:29:00+00:00",
        "make": "NIKON",
        "megapixels": 0.307,
        "model": "COOLPIX P6000",
        "orientation": "Horizontal (normal)",
        "resolution_unit": "inches",
        "software": "Nikon Transfer 1.1 W",
        "x_resolution": 300,
        "y_resolution": 300
    },
    "technical": {
        "aperture": 4.5,
        "brightness": 0,
        "contrast": "Normal",
        "digital_zoom": 1,
        "digital_zoom_ratio": 0,
        "distortion_control": "Off",
        "exposure_compensation": 0,
        "exposure_mode": "Auto",
        "exposure_program": "Program AE",
        "exposure_time": "1/178",
        "f_number": 4.5,
        "filter_effect": null,
        "flash": "Off, Did not fire",
        "flash_setting": null,
        "focal_length": "6.0 mm",
        "focal_length_in_35mm_format": "28 mm",
        "focus_mode": "AF-S",
        "fov": "65.5 deg",
        "gain_control": "None",
        "hyperfocal_distance": "1.24 m",
        "iso": 64,
        "light_source": null,
        "light_value": 12.5,
        "max_aperture_value": 2.7,
        "noise_reduction": "Off",
        "saturation": "Normal",
        "scale_factor_35efl": 4.7,
        "scene_capture_type": "Standard",
        "scene_mode": null,
        "scene_type": "Directly photographed",
        "sharpness": "Normal",
        "shutter_speed": "1/178",
        "shutter_speed_value": null,
        "white_balance": "Auto"
    },
    "gps": {
        "gps_date_time": "2008-10-23T14:28:00+00:00",
        "gps_latitude": 43.46716,
        "gps_latitude_ref": "N",
        "gps_longitude": 11.88539,
        "gps_longitude_ref": "E",
        "gps_satellites": "06"
    }
}