var JSONallOutput200 = {
    "file": {
        "bits_per_sample": 8,
        "file_access_date": "2018-03-02 23:53:53 +0100",
        "file_modify_date": "2018-03-01 07:49:55 +0100",
        "file_name": "test.jpg",
        "file_size": "11 kB",
        "file_type": "JPEG",
        "image_height": 75,
        "image_size": "100x75",
        "image_width": 100,
        "mime_type": "image/jpeg",
        "user_comment": null
    },
    "camera": {
        "compression": "JPEG (old-style)",
        "date_time_original": "2008-07-16 11:33:20 +0200",
        "make": "Panasonic",
        "megapixels": 0.007,
        "model": "DMC-FZ30",
        "orientation": "Horizontal (normal)",
        "resolution_unit": "inches",
        "software": "GIMP 2.4.5",
        "x_resolution": 72,
        "y_resolution": 72
    },
    "technical": {
        "aperture": 3.2,
        "brightness": null,
        "contrast": "Normal",
        "digital_zoom": null,
        "digital_zoom_ratio": 0,
        "distortion_control": null,
        "exposure_compensation": 0,
        "exposure_mode": "Auto",
        "exposure_program": "Program AE",
        "exposure_time": "1/30",
        "f_number": 3.2,
        "filter_effect": null,
        "flash": "On, Fired",
        "flash_setting": null,
        "focal_length": "14.1 mm",
        "focal_length_in_35mm_format": "82 mm",
        "focus_mode": "Auto",
        "fov": "24.8 deg",
        "gain_control": "None",
        "hyperfocal_distance": "12.03 m",
        "iso": 100,
        "light_source": "Flash",
        "light_value": 8.3,
        "max_aperture_value": 2.8,
        "noise_reduction": "Standard",
        "saturation": "Normal",
        "scale_factor_35efl": 5.8,
        "scene_capture_type": "Standard",
        "scene_mode": null,
        "scene_type": "Directly photographed",
        "sharpness": "Normal",
        "shutter_speed": "1/30",
        "shutter_speed_value": null,
        "white_balance": "Auto"
    },
    "gps": {
        "gps_date_time": null,
        "gps_latitude": null,
        "gps_latitude_ref": null,
        "gps_longitude": null,
        "gps_longitude_ref": null,
        "gps_satellites": null
    }
}
