var JSONrawOutput200 = {
    "active_d_lighting": "Off",
    "af_area_mode": "Single Area",
    "af_point": "Center",
    "af_points_in_focus": "(none)",
    "aperture": 4.5,
    "auxiliary_lens": "Off",
    "bits_per_sample": 8,
    "brightness": null,
    "circle_of_confusion": "0.006 mm",
    "color_components": 3,
    "color_mode": "Color",
    "color_space": "sRGB",
    "components_configuration": "Y, Cb, Cr, -",
    "compression": "JPEG (old-style)",
    "contrast": "Normal",
    "create_date": "2008-10-22 16:29:49 +0200",
    "custom_rendered": "Normal",
    "date_time_original": "2008-10-22 16:29:49 +0200",
    "digital_zoom": 1,
    "digital_zoom_ratio": 0,
    "distortion_control": "Off",
    "encoding_process": "Baseline DCT, Huffman coding",
    "exif_byte_order": "Little-endian (Intel, II)",
    "exif_image_height": 480,
    "exif_image_width": 640,
    "exif_tool_version": 10.25,
    "exif_version": 220,
    "exposure_compensation": 0,
    "exposure_mode": "Auto",
    "exposure_program": "Program AE",
    "exposure_time": "1/178",
    "f_number": 4.5,
    "face_detect_frame_size": "320 240",
    "faces_detected": 0,
    "file_access_date": "2018-03-03 22:50:12 +0100",
    "file_inode_change_date": "2018-03-03 18:49:55 +0100",
    "file_modify_date": "2018-03-03 17:55:51 +0100",
    "file_permissions": "rw-rw-r--",
    "file_size": "155 kB",
    "file_source": "Digital Camera",
    "file_type": "JPEG",
    "file_type_extension": "jpg",
    "filter_effect": null,
    "flash": "Off, Did not fire",
    "flash_setting": null,
    "flashpix_version": 100,
    "focal_length": "6.0 mm",
    "focal_length35efl": "6.0 mm (35 mm equivalent: 28.0 mm)",
    "focal_length_in35mm_format": "28 mm",
    "focus_mode": "AF-S",
    "fov": "65.5 deg",
    "gain_control": "None",
    "gps_altitude_ref": "Above Sea Level",
    "gps_date_stamp": "2008:10:23",
    "gps_date_time": "2008-10-23 14:28:17 UTC",
    "gps_img_direction_ref": null,
    "gps_latitude": "43 deg 28' 1.76\" N",
    "gps_latitude_ref": "North",
    "gps_longitude": "11 deg 53' 7.42\" E",
    "gps_longitude_ref": "East",
    "gps_map_datum": "WGS-84   ",
    "gps_position": "43 deg 28' 1.76\" N, 11 deg 53' 7.42\" E",
    "gps_satellites": "06",
    "gps_time_stamp": "14:28:17.24",
    "hue_adjustment": null,
    "hyperfocal_distance": "1.24 m",
    "image_adjustment": "Normal",
    "image_description": "                               ",
    "image_height": 480,
    "image_size": "640x480",
    "image_stabilization": "VR-On",
    "image_width": 640,
    "interop_index": "R98 - DCF basic file (sRGB)",
    "interop_version": 100,
    "iso": 64,
    "iso_selection": "Auto",
    "light_source": null,
    "light_value": 12.5,
    "make": "NIKON",
    "maker_note_version": 2.1,
    "max_aperture_value": 2.7,
    "megapixels": 0.307,
    "metering_mode": "Multi-segment",
    "mime_type": "image/jpeg",
    "model": "COOLPIX P6000",
    "modify_date": "2008-11-01 21:15:07 +0100",
    "nef_bit_depth": "n/a (JPEG)",
    "nikon_capture_version": "COOLPIX P6000V1.0              ",
    "noise_reduction": "Off",
    "orientation": "Horizontal (normal)",
    "picture_control_adjust": "Default Settings",
    "picture_control_base": "Standard",
    "picture_control_name": "Standard",
    "picture_control_quick_adjust": "Normal",
    "picture_control_version": 100,
    "quality": "Fine",
    "rating_percent": 0,
    "resolution_unit": "inches",
    "retouch_history": "None",
    "saturation": "Normal",
    "scale_factor35efl": 4.7,
    "scene_assist": null,
    "scene_capture_type": "Standard",
    "scene_mode": null,
    "scene_type": "Directly photographed",
    "sharpness": "Normal",
    "shutter_speed": "1/178",
    "software": "Nikon Transfer 1.1 W",
    "subject_distance_range": null,
    "thumbnail_length": 6339,
    "thumbnail_offset": 4560,
    "tone_comp": "Normal",
    "toning_effect": null,
    "toning_saturation": null,
    "user_comment": null,
    "white_balance": "Auto",
    "x_resolution": 300,
    "xmp_toolkit": "Public XMP Toolkit Core 3.5",
    "y_cb_cr_positioning": "Centered",
    "y_cb_cr_sub_sampling": "YCbCr4:2:2 (2 1)",
    "y_resolution": 300
}